name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure Safe Python 3.9 Path
        run: |
          mkdir -p $HOME/bin
          ln -sf $(which python) $HOME/bin/python3
          ln -sf $(which python) $HOME/bin/python
          echo "$HOME/bin" >> $GITHUB_PATH
          python --version
          python3 --version

      - name: Set up Swap Space
        run: |
          sudo swapoff /swapfile || true
          sudo rm -f /swapfile
          sudo dd if=/dev/zero of=/swapfile bs=1M count=4096 status=progress
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install dependencies
        run: |
          # إزالة أداة command-not-found لمنع مشكلة خطأ apt_pkg نهائياً
          sudo apt-get remove -y command-not-found || true
          sudo apt-get update
          sudo apt-get install -y \
              python3-pip \
              build-essential \
              git \
              python3-dev \
              ffmpeg \
              libsdl2-dev \
              libsdl2-image-dev \
              libsdl2-mixer-dev \
              libsdl2-ttf-dev \
              libportmidi-dev \
              libswscale-dev \
              libavformat-dev \
              libavcodec-dev \
              zlib1g-dev \
              ant \
              openjdk-17-jdk \
              autoconf \
              libtool \
              pkg-config \
              libncurses5-dev \
              libstdc++6 \
              libglu1-mesa-dev \
              unzip \
              zip

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "setuptools<=65.5.0" cython==0.29.32 buildozer

      - name: Build with Buildozer
        run: |
          export CFLAGS="-Wno-error"
          export MAKEFLAGS="-j1"
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
